### ISSUE TITLE
Shown archived tasks that I don't own on

### ISSUE THREAD

**Issue by 3ygun** [J3RN/timesheet#22]
I just signed into the app went to tasks and was shown:

![capture](https://cloud.githubusercontent.com/assets/5482320/13594078/67ff2e24-e4cf-11e5-97a3-900d688184db.PNG)

I can see but NOT edit or unarchive them (didn't try delete :D ).

**Comment by J3RN** [comment]
It's the line where archived tasks are `unscoped`. That thing has been a pain in the ass. I'll fix this at my next available opportunity.
