### ISSUE TITLE
Switch from Bootstrap to Bourbon?

### ISSUE THREAD

**Issue by J3RN** [J3RN/timesheet#30]
## The Problem

The site currently uses [Bootstrap](http://getbootstrap.com) to do a majority of the styling. That's well and good, but I feel like Bootstrap has been getting in the way of mobile optimizing the site. For the life of me, I cannot figure out the incantations to get the container to not force everything to be super tiny on mobile.

Furthermore, Bootstrap sort of mucks up the HTML/ERB, and results in things like:
```html
<!-- app/views/devise/sessions/new.html.erb -->
<div class="panel panel-default devise-panel col-md-4 col-sm-10 col-md-offset-4 col-sm-offset-1">
  ...
</div>
```
Which must be copied-and-pasted to every darned thing you want to look like that.

## The Solution

I have, a number of times, used [Bourbon](http://bourbon.io) and [Neat](http://neat.bourbon.io) as an alternative to Bootstrap. Bourbon leverages Sass to allow you compose it's built-in functions to create new components.

For example, take the above code. The Bourbon equivalent would be:

```html
<!-- app/views/devise/sessions/new.html.erb -->
<div class="centered-panel">
  ...
</div>
```

```sass
/* app/assets/stylesheets/_components.scss */
.centered-panel {
  @include span-columns(4);
  @include shift(4);

  @include media($mobile) {
    @include span-columns(10);
    @include shift(1);
  }
}
```

While it's *more* code, it's *better* code. And besides, to make another element look just like that one, all you have to do is set `class="centered-panel"` on that element.

All in all, I think it's a worthwhile tradeoff. I'd love to hear what you think @3ygun @JohnSimerlink.

**Comment by jemagee** [comment]
I happened upon your project last night while looking for projects to possibly contribute on, so take my two cents as it is because I'm not great with layout, but doesn't bootstrap also leverage sass and allow you to build your own classes like your bourbon neat example?  I have extended / used built in bootstrap to build my own classes in the past, I don't see why you couldn't build your 'centered-panel' class using sass and bootstrap as well...or at least trying that first before switching to an entirely new platform?  One way or another, refactoring the css stuff will take time but I'd think it'd take less time to refactor bootstrap than to switch to something entirely new.

Plus [Bootstrap 4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) might solve some of the issues your having with the responsiveness?

**Comment by 3ygun** [comment]
Hello @jemagee!

I agree that a possible combination of the 2 might be a better option then a complete rip-out and replacement. However, then again right now there aren't that many pages/that much CSS so I don't think it would be that much of a problem. And I'm open to learning more new stuff!: D

**Comment by J3RN** [comment]
@jemagee Hey there! I'm glad you found us. I'm, of course, always welcome to suggestions and contributions.

I did a little googling about leveraging Bootstrap's Sass port to do the same sorts of stuff, but I wasn't able to find any great documentation on it. I did see a few bits on doing it with Bootstrap's Less implementation. Do you have a link you could share so I could look into it further?

@3ygun I believe, if I am not mistaken, that we are talking about using Bootstrap to do the same sort of thing I was talking about doing with Bourbon+Neat, but with Bootstrap alone, not mixing the two. I'm afraid that having two layout systems would cause all sort of muck.

**Comment by 3ygun** [comment]
@J3RN when I said "mixing of the 2" I meant following @jemagee 's idea of further defining scss stuff for our current Bootstrap styles. However if, as you said, there isn't good documentation for way of doing things I'm fine with transitioning to Bourbon+Neat

**Comment by jemagee** [comment]
I’m mostly a back end guy and i have successfully integrated sass stuff into bootstrap in the past.

It seems to me like you just need to use @extend a lot within your custom field definition to pull in all the bootstrap column settings.  I’d try that first

**Comment by jemagee** [comment]
I can try a quick experiment to see if this works for you. I'm still in the, what I call, intermediate beginner range and working on a few of my own processes, but I'll give this a shot tonight after work (I'm in California) and see if it works out.

**Comment by J3RN** [comment]
@jemagee Sounds good! :+1:

**Comment by jemagee** [comment]
Not really sure it's worth a pull request - but it seemed to work for me.

Put this in your application.scss file

`.centered-panel {
  @extend .panel, .panel-default, .devise-panel, .col-md-4, .col-sm-10, .col-md-offset-4, .col-sm-offset-1
}`

Alter the new session view and it should still work the same way (tested using my imac/firefox and resizing the window).  It's pretty simple (when I found the fact that you could use @extend on numerous classes at once by separating them with the commas.

And of course, then you could use @extend on .centered-panel if you wanted to add a bit more to something else (background, different buttons, anything)

**Comment by J3RN** [comment]
Excellent! I should have looked into `@extend` earlier. In that case, I'd be happy to go on using Bootstrap. Closing this issue.
