### ISSUE TITLE
Keybinding for new tasks/time entries/tags

### ISSUE THREAD

**Issue by J3RN** [J3RN/timesheet#36]
I think it would be nifty to have a keybinding to create a new whatever, based on what page you're on. For example, if you are on the "Time Entries" page, it would be nice to have a keybinding to take you to the new time entry page.

The Flip Side&trade;: I like allowing users to use their own, custom ways of getting around sites, like Vimperator. Having a keybinding will probably conflict with Vimperator, like GitHub's do.

What do you think?

**Comment by J3RN** [comment]
I've decided to go ahead with this one

**Comment by harman28** [comment]
@J3RN Attempted to resolve this in #79. Please take a look when convenient.

**Comment by J3RN** [comment]
Closed by #79
