### ISSUE TITLE
Name!?

### ISSUE THREAD

**Issue by J3RN** [J3RN/timesheet#5]
So the app is inconsistent as to whether its name is "timesheet" or "Time Tracker". I have a very slight preference for the latter, but would appreciate any feedback. Also alternate suggestions are totally welcome.

**Comment by 3ygun** [comment]
Time Tracker feels more productive personally :+1:

**Comment by J3RN** [comment]
I'm also wondering if there's a catchier/more appropriate name out there. After all, this app is more than just a timesheet/time tracker anyway - it's a combined ToDo list and time tracker.

**Comment by J3RN** [comment]
Someone proposed to me yesterday the idea of using a completely unrelated name that is catchy, sort of like "Toggl" (as in the mildly-relatedness, not using a name similar to "Toggl"). He suggested "AWOL", which is catchy, but I'm not sure if it's even mildly related.

**Comment by J3RN** [comment]
Rolling with "Time Tracker" for now.
