### ISSUE TITLE
Change the duration displays to better format

### ISSUE THREAD

**Issue by J3RN** [J3RN/timesheet#67]
Currently, there are two methods (a short format and a long format) in `ApplicationHelper` that render durations. I'd like to switch to just using one format, "hh:mm".

E.g. If you've worked on something for one and a half hours: "01:30"

**Comment by IamAdiSri** [comment]
Hey, I'd like to work on this, but i'm not sure i've understood the issue. Reading through the code i found two functions which render durations. To only take one format, wouldn't removing one of the functions be  enough?

**Comment by J3RN** [comment]
@IamAdiSri Hi there! :wave: I'm glad to hear that you're interested in working on this issue.

You're right! It would be necessary to remove one of the methods (let's say `long_duration_display`), and replace all uses of that method with the other method (`duration_display`).

Also, the current `duration_display` method returns a string that looks like "1h30m" to indicate a duration of 1 hour and 30 minutes. I'd like to have that method return "01:30" instead of "1h30m".

**Comment by yock** [comment]
@J3RN I don't quite understand your app well enough to run it locally, so I'd be grateful for feedback from some interactive testing on your part. I think this should do what you need though.

**Comment by J3RN** [comment]
@yock Thanks for your PR! I'll review those changes over there.

Did you run into errors following the instructions in the README?

**Comment by yock** [comment]
@J3RN Truth be told, I just don't have Postgres running on my machine at the moment.

**Comment by IamAdiSri** [comment]
@J3RN  I just wanted to mention that I did claim the issue first. I can hardly say anything now that yock has made a PR but the project maintainers should make sure that in the future, priority is given to contributors in the order in which they claim the issue.

@yock Please ask if somebody is already working on an issue before making a PR or beginning work on it yourself.
